services:
  minio:
    container_name: minio_storage
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  db:
    image: postgres:15
    container_name: aspirin_postgres
    restart: always
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aspirin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: aspirin_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  minio-data:
  pgdata: